# Generated by Django 5.1.7 on 2025-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employee_department_alter_employee_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.CharField(default=123456789, max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='user@user.com', max_length=255),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='user', max_length=255),
        ),
    ]
