# Generated by Django 5.1.7 on 2025-04-02 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_contact_employee_email_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='shift_type',
        ),
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='attendance',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='hours_worked',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='leave_status',
            field=models.CharField(default='Present', max_length=20),
        ),
    ]
